import { useViewerStore } from "../store.js";
import { JsonTree } from "../JsonTree.jsx";
import { Panel } from "../controls.jsx";

export function CreditsTab({ onCollapse }) {
    const assetCopyright = useViewerStore((state) => state.assetCopyright);
    const assetGenerator = useViewerStore((state) => state.assetGenerator);
    const environmentLicense = useViewerStore((state) => state.environmentLicense);
    const xmp = useViewerStore((state) => state.xmp);

    return (
        <Panel title="Model Credits" onCollapse={onCollapse}>
            <div className="my-6 break-words">
                <i>Copyright:</i>
                <br />
                <span data-testid="asset-copyright">{assetCopyright}</span>
            </div>
            <div className="my-6 break-words">
                <i>Generated by:</i>
                <br />
                <span data-testid="asset-generator">{assetGenerator}</span>
            </div>

            <h2 className="mt-12 mb-4 text-[22pt] leading-tight font-bold">Environment Credits</h2>
            <div className="my-6 break-words">
                <i>Copyright:</i>
                <br />
                <p data-testid="environment-license">
                    {environmentLicense ? (
                        <>
                            (c) {environmentLicense.copyright},{" "}
                            <a href={environmentLicense.sourceUrl}>Source</a>, License:{" "}
                            <a href={environmentLicense.licenseUrl}>
                                {environmentLicense.licenseName}
                            </a>
                        </>
                    ) : (
                        "N/A"
                    )}
                </p>
            </div>

            {xmp && <h3 className="mt-12 mb-4 text-xl font-bold">XMP</h3>}
            <JsonTree data={xmp} />
        </Panel>
    );
}
