import { useViewerStore } from "../store.js";
import { JsonTree } from "../JsonTree.jsx";
import { Panel, Subtitle } from "../controls.jsx";

function Credit({ label, children, ...rest }) {
    return (
        <div className="my-4 break-words">
            <p className="text-ink/60 text-sm">{label}</p>
            <p {...rest}>{children}</p>
        </div>
    );
}

export function CreditsTab({ onCollapse }) {
    const assetCopyright = useViewerStore((state) => state.assetCopyright);
    const assetGenerator = useViewerStore((state) => state.assetGenerator);
    const environmentLicense = useViewerStore((state) => state.environmentLicense);
    const xmp = useViewerStore((state) => state.xmp);

    return (
        <Panel title="Model Credits" onCollapse={onCollapse}>
            <Credit label="Copyright" data-testid="asset-copyright">
                {assetCopyright}
            </Credit>
            <Credit label="Generated by" data-testid="asset-generator">
                {assetGenerator}
            </Credit>

            <Subtitle>Environment Credits</Subtitle>
            <Credit label="Copyright" data-testid="environment-license">
                {environmentLicense ? (
                    <>
                        (c) {environmentLicense.copyright},{" "}
                        <a href={environmentLicense.sourceUrl}>Source</a>, License:{" "}
                        <a href={environmentLicense.licenseUrl}>{environmentLicense.licenseName}</a>
                    </>
                ) : (
                    "N/A"
                )}
            </Credit>

            {xmp && <Subtitle>XMP</Subtitle>}
            <JsonTree data={xmp} />
        </Panel>
    );
}
