import { useViewerStore } from "../store.js";
import { JsonTree } from "../JsonTree.jsx";

export function CreditsTab({ onCollapse }) {
    const assetCopyright = useViewerStore((state) => state.assetCopyright);
    const assetGenerator = useViewerStore((state) => state.assetGenerator);
    const environmentLicense = useViewerStore((state) => state.environmentLicense);
    const xmp = useViewerStore((state) => state.xmp);

    return (
        <div className="tabContent">
            <img src="assets/ui/Navigation_right_20px.svg" width="30px" onClick={onCollapse} />
            <h2 className="title">Model Credits</h2>
            <div className="modelCredit">
                <i>Copyright:</i>
                <br />
                <span data-testid="asset-copyright">{assetCopyright}</span>
            </div>
            <div className="modelCredit">
                <i>Generated by:</i>
                <br />
                <span data-testid="asset-generator">{assetGenerator}</span>
            </div>

            <h2 className="title">Environment Credits</h2>
            <div className="modelCredit">
                <i>Copyright:</i>
                <br />
                <p data-testid="environment-license">
                    {environmentLicense ? (
                        <>
                            (c) {environmentLicense.copyright},{" "}
                            <a href={environmentLicense.sourceUrl}>Source</a>, License:{" "}
                            <a href={environmentLicense.licenseUrl}>
                                {environmentLicense.licenseName}
                            </a>
                        </>
                    ) : (
                        "N/A"
                    )}
                </p>
            </div>

            <h3 className="title">{xmp ? "XMP" : ""}</h3>
            <JsonTree data={xmp} />
        </div>
    );
}
